# Server
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gestion?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jackson.deserialization.FAIL_ON_UNKNOWN_PROPERTIES=true

# JWT
jwt.secret=CafeteriaUIDE2024SecureKey!@#$%

# Google OAuth
google.oauth.client-id=339531515746-hen1n6icqtm6n1labk58e5im13bvhv84.apps.googleusercontent.com

# Upload limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.tics.uide.gestionuide=INFO
logging.level.org.hibernate.SQL=WARN


# Email / SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jeferalo.0210@gmail.com
spring.mail.password=ndgvcvbqmqhspqbe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8